[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about/index.html"
  status = 200

[[redirects]]
  from = "/blog/"
  to = "/blog"
  status = 301
  force = true

[[redirects]]
  from = "/about/"
  to = "/about"
  status = 301
  force = true

[[redirects]]
  from = "/blog/:slug/"
  to = "/blog/:slug"
  status = 301
  force = true

[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "index, follow"
